#include "scenes/GameScene.hpp"

#include <array>
#include <cmath>
#include <memory>
#include <string>
#include <unordered_set>

#include <glm/glm.hpp>

#include "Core/Context.hpp"

#include "Util/Collider.hpp"
#include "Util/Image.hpp"
#include "Util/Input.hpp"
#include "Util/Keycode.hpp"
#include "Util/Logger.hpp"
#include "Util/Position.hpp"
#include "Util/TransformUtils.hpp"

namespace Game {
namespace {
constexpr float kPlayerRadius = 16.0F;
constexpr float kBulletSpeedScale = 15.0F; // data bullet_speed -> pixels/second
constexpr float kBulletLifeMs = 1500.0F;
constexpr float kEnemyBulletSpeed = 300.0F;
constexpr float kEnergyRegenMs = 400.0F; // +1 energy per interval
constexpr int kEnemyContactDamage = 1;
// repel(data, ~1-3) -> pre-clamp impulse; >=1 saturates the 28/30 GetForce cap,
// matching the original where most hits land at the cap. Tunable (see report).
constexpr float kRepelScale = 30.0F;
// World size (pixels) of one RoomGen grid cell.
constexpr float kCellPx = 32.0F;
// Fixed room footprint (cells) so rooms tile edge-to-edge and their door gaps
// align between neighbours; pitch is the world distance between room centres.
constexpr int kRoomCells = 15;
constexpr float kRoomPitch = static_cast<float>(kRoomCells) * kCellPx;
// Player must be this close (px) to auto-open a chest / collect a pickup.
constexpr float kChestOpenRange = 40.0F;
constexpr float kPickupRange = 28.0F;
// Boss body radius for wall collision; boss fan spread (degrees).
constexpr float kBossBodyRadius = 24.0F;
constexpr float kBossFanSpreadDeg = 30.0F;

glm::vec2 Normalize(glm::vec2 v) {
    const float len = std::sqrt(v.x * v.x + v.y * v.y);
    return len > 0.0F ? v / len : glm::vec2(0.0F, 0.0F);
}
} // namespace

GameScene::GameScene()
    : m_BulletPool(0, [] {
          return std::make_shared<Bullet>(std::string(RESOURCE_DIR));
      }) {}

void GameScene::OnEnter() {
    const std::string root = RESOURCE_DIR;
    m_Data.LoadAll(root);
    m_Loot.LoadAll(root); // chest droptables

    // Root every deterministic stream this run owns in the run seed.
    m_Rng.SetRandomSeed(m_RunSeed);
    m_Sim.emplace(m_RunSeed, this); // headless sim driven from Update; `this` is the WorldCollision.

    m_Background = std::make_shared<Util::GameObject>();
    m_Background->SetDrawable(
        std::make_shared<Util::Image>(root + "/sprites/Background.png"));
    m_Background->SetZIndex(0.0F);

    m_Player = std::make_shared<Player>(m_Data.PlayerTemplate(), root);

    // --- Procedural floor: a MapManager random-walk lays out the rooms; each is
    // generated by RoomGen with door openings toward its placed neighbours and
    // tiled edge-to-edge (fixed size) so the door gaps line up and the player can
    // walk between rooms. Deterministic from the run seed.
    MapManager::Options mapOpt;
    mapOpt.mapLong = 7;
    mapOpt.ranRoomProbability = 25;
    const MapManager floor(m_RunSeed, mapOpt);
    const RoomCell &startCell = floor.Rooms()[floor.StartIndex()];
    const int startGx = startCell.gridX;
    const int startGy = startCell.gridY;

    // The room farthest (Manhattan) from the start becomes the boss room.
    int bossRoom = floor.StartIndex();
    int bestDist = -1;
    for (std::size_t i = 0; i < floor.Rooms().size(); ++i) {
        int dx = floor.Rooms()[i].gridX - startGx;
        int dy = floor.Rooms()[i].gridY - startGy;
        const int dist = (dx < 0 ? -dx : dx) + (dy < 0 ? -dy : dy);
        if (dist > bestDist) {
            bestDist = dist;
            bossRoom = static_cast<int>(i);
        }
    }

    const EnemyDef *edef = m_Data.FindEnemy("EnemyAI01");
    int roomIndex = 0;
    for (const RoomCell &cell : floor.Rooms()) {
        const glm::vec2 origin{
            static_cast<float>(cell.gridX - startGx) * kRoomPitch,
            static_cast<float>(cell.gridY - startGy) * kRoomPitch};

        RoomGen::Options ropt;
        ropt.randomRoom = false; // fixed size so rooms tile + doors align
        ropt.roomWidth = kRoomCells;
        ropt.roomHeight = kRoomCells;
        ropt.wallLevel = cell.type >= 2 ? 2 : 1; // richer obstacles in special rooms
        ropt.obstacleLevel = 1;
        const RoomGen rg(m_RunSeed + 1 + roomIndex, cell.entrance, ropt);

        m_Rooms.push_back(
            std::make_unique<Room>(Room::FromRoomGen(rg, kCellPx, origin)));

        for (int x = 0; x < rg.Width(); ++x) {
            for (int y = 0; y < rg.Height(); ++y) {
                if (!Room::IsSolidCell(rg.At(x, y))) {
                    continue;
                }
                auto img =
                    std::make_shared<Util::Image>(root + "/sprites/box01.png");
                const glm::vec2 sz = img->GetSize();
                auto tile = std::make_shared<Util::GameObject>();
                tile->SetDrawable(img);
                tile->SetZIndex(1.0F);
                tile->m_Transform.translation = Room::CellToWorld(
                    x, y, rg.Width(), rg.Height(), kCellPx, origin);
                if (sz.x > 0.0F && sz.y > 0.0F) {
                    tile->m_Transform.scale =
                        glm::vec2(kCellPx / sz.x, kCellPx / sz.y);
                }
                m_RoomTiles.push_back(tile);
                m_Renderer.AddChild(tile);
            }
        }

        // Collect this room's door-gap cells (code 11) as colliders, sealed
        // while the room is the active uncleared room (clear-room gating).
        std::vector<Util::Collider> doors;
        for (int x = 0; x < rg.Width(); ++x) {
            for (int y = 0; y < rg.Height(); ++y) {
                if (rg.At(x, y) == 11) {
                    doors.push_back(Util::Collider::MakeAABB(
                        Room::CellToWorld(x, y, rg.Width(), rg.Height(), kCellPx,
                                          origin),
                        glm::vec2{kCellPx, kCellPx}));
                }
            }
        }
        m_RoomDoors.push_back(std::move(doors));

        // Boss room gets a boss; every other non-start room gets one enemy.
        if (roomIndex != floor.StartIndex() && !rg.FloorList().empty()) {
            const auto &fc = rg.FloorList()[rg.FloorList().size() / 2];
            const glm::vec2 spawn = Room::CellToWorld(
                fc.first, fc.second, rg.Width(), rg.Height(), kCellPx, origin);
            if (roomIndex == bossRoom) {
                auto boss = std::make_shared<Boss>(root, spawn, /*maxHp=*/500,
                                                   /*shootCd=*/2.0F,
                                                   m_RunSeed + 9000);
                boss->SetRoomId(roomIndex);
                m_Bosses.push_back(boss);
                m_Sim->SetBoss(2.0F, spawn, /*maxHp=*/500, roomIndex, m_RunSeed + 9000);
            } else if (edef != nullptr) {
                auto enemy =
                    std::make_shared<Enemy>(*edef, root, spawn, 450.0F, 260.0F);
                enemy->AI().SetSeed(m_RunSeed + 1000 + roomIndex);
                enemy->AI().SetKinematic(edef->kinematic != 0);
                enemy->SetRoomId(roomIndex);
                m_Enemies.push_back(enemy);
                m_Sim->AddEnemy(*edef, spawn, roomIndex, m_RunSeed + 1000 + roomIndex);
            }
        }

        // Place a chest in every non-start room on a floor cell (tier = room
        // type, so special/badass rooms roll richer loot).
        if (roomIndex != floor.StartIndex() && !rg.FloorList().empty()) {
            const auto &cc = rg.FloorList()[rg.FloorList().size() / 4];
            const glm::vec2 cpos = Room::CellToWorld(
                cc.first, cc.second, rg.Width(), rg.Height(), kCellPx, origin);
            auto chest = std::make_shared<Chest>(root, cpos, cell.type);
            m_Chests.push_back(chest);
            m_Renderer.AddChild(chest);
        }
        ++roomIndex;
    }

    if (const WeaponDef *wdef = m_Data.FindWeapon("Gun001")) {
        m_Weapon = std::make_unique<WeaponInstance>(*wdef); // OLD path, removed in Task 3.
        m_Sim->EquipWeapon(*wdef, "Gun001", m_RunSeed + 5);
        m_WeaponEnergyCost = wdef->consume > 0 ? wdef->consume : 1;
    }

    m_Renderer.AddChild(m_Background);
    m_Renderer.AddChild(m_Player);
    for (const auto &enemy : m_Enemies) {
        m_Renderer.AddChild(enemy);
    }
    for (const auto &boss : m_Bosses) {
        m_Renderer.AddChild(boss);
    }

    m_Camera.SetPosition(m_Player->Position());
    LOG_INFO("GameScene: multi-room floor ready");
}

glm::vec2 GameScene::AimDirection() const {
    // GetCursorPosition returns a PTSDPosition; keep it typed to avoid the
    // deprecated implicit PTSDPosition -> glm::vec2 conversion (MSVC C4996).
    const Util::PTSDPosition cursor =
        Util::Input::GetCursorPosition(); // screen px (y down)
    const Util::PTSDPosition w = Util::PTSDPosition::FromSDL(
        static_cast<int>(cursor.x), static_cast<int>(cursor.y));
    // The camera center maps to the screen center, so the world point under the
    // cursor is the camera position plus the cursor's center-origin offset.
    const glm::vec2 worldCursor = m_Camera.GetPosition() + glm::vec2(w.x, w.y);
    return Normalize(worldCursor - m_Player->Position());
}

void GameScene::TryFirePlayerWeapon() {
    if (m_Weapon == nullptr || !m_Weapon->Ready()) {
        return;
    }
    if (!m_Player->Stats().SpendEnergy(m_Weapon->EnergyCost())) {
        return; // not enough energy
    }
    m_Weapon->TryFire();

    // Faithful multi-bullet fire: one trigger pull -> N deviation-jittered bullets
    // (single/spread/shotgun), each carrying atk/repel/critical/pierce.
    const FirePlan plan = m_Weapon->BuildFirePlan(AimDirection(), m_Rng);
    for (const BulletSpawn &bs : plan.bullets) {
        auto bullet = m_BulletPool.Acquire();
        bullet->Init(m_Player->Position(), bs.velocity * kBulletSpeedScale,
                     kBulletLifeMs, bs.damage, /*camp=*/0, bs.repel, bs.critical,
                     bs.canThrough, bs.pierce);
        m_Renderer.AddChild(bullet);
        m_Bullets.push_back(bullet);
    }
}

void GameScene::UpdateBullets(float dtMs) {
    for (auto it = m_Bullets.begin(); it != m_Bullets.end();) {
        auto &bullet = *it;
        bullet->Update(dtMs);

        if (bullet->Active()) {
            if (bullet->Camp() == 0) {
                for (auto &enemy : m_Enemies) {
                    if (enemy->IsDead() ||
                        !Util::Overlap(bullet->GetCollider(),
                                       enemy->GetCollider())) {
                        continue;
                    }
                    // Faithful attacker-side resolution: damage factor, crit
                    // roll, crit scaling, repel (doubled on crit, capped). Enemy
                    // takes it straight to HP (no armor).
                    Combat::AttackerInput in;
                    in.baseDamage = bullet->Damage();
                    in.critical = bullet->Critical();
                    in.repelInputMagnitude = bullet->Repel() * kRepelScale;
                    const Combat::HitResult hr = Combat::ResolveHit(
                        in, m_Rng, Combat::Defender::ENEMY);
                    Combat::ApplyToEnemy(enemy->MutableStats(), hr,
                                         /*canHurt=*/true);
                    if (hr.repelMagnitude > 0.0F) {
                        enemy->AI().GetForce(Normalize(bullet->Velocity()),
                                             hr.repelMagnitude);
                    }
                    if (bullet->ConsumePierce()) {
                        bullet->Deactivate();
                    }
                    break; // one enemy hit per bullet per frame
                }
                if (bullet->Active()) {
                    for (auto &boss : m_Bosses) {
                        if (boss->IsDead() ||
                            !Util::Overlap(bullet->GetCollider(),
                                           boss->GetCollider())) {
                            continue;
                        }
                        Combat::AttackerInput in;
                        in.baseDamage = bullet->Damage();
                        in.critical = bullet->Critical();
                        in.repelInputMagnitude = bullet->Repel() * kRepelScale;
                        const Combat::HitResult hr = Combat::ResolveHit(
                            in, m_Rng, Combat::Defender::ENEMY);
                        boss->TakeDamage(hr.finalDamage);
                        if (bullet->ConsumePierce()) {
                            bullet->Deactivate();
                        }
                        break;
                    }
                }
            } else if (bullet->Camp() == 1) {
                const Util::Collider playerHit =
                    Util::Collider::MakeCircle(m_Player->Position(),
                                               kPlayerRadius);
                if (Util::Overlap(bullet->GetCollider(), playerHit)) {
                    // Player defender: armor-then-HP via the faithful chain.
                    Combat::AttackerInput in;
                    in.baseDamage = bullet->Damage();
                    in.critical = bullet->Critical();
                    in.repelInputMagnitude = bullet->Repel() * kRepelScale;
                    const Combat::HitResult hr = Combat::ResolveHit(
                        in, m_Rng, Combat::Defender::PLAYER);
                    Combat::ApplyToPlayer(m_Player->Stats(), hr, /*canHurt=*/true);
                    bullet->Deactivate();
                }
            }
        }

        if (!bullet->Active()) {
            m_Renderer.RemoveChild(bullet);
            m_BulletPool.Release(bullet);
            it = m_Bullets.erase(it);
        } else {
            ++it;
        }
    }
}

bool GameScene::BlocksAny(glm::vec2 pos, float radius) const {
    for (const auto &room : m_Rooms) {
        if (room->Blocks(pos, radius)) {
            return true;
        }
    }
    // Sealed doors of the active uncleared room block both player and enemies.
    if (m_LockedRoom >= 0 && m_LockedRoom < static_cast<int>(m_RoomDoors.size())) {
        const Util::Collider circle = Util::Collider::MakeCircle(pos, radius);
        for (const Util::Collider &door :
             m_RoomDoors[static_cast<std::size_t>(m_LockedRoom)]) {
            if (Util::Overlap(door, circle)) {
                return true;
            }
        }
    }
    return false;
}

void GameScene::SyncBulletViews() {
    const std::vector<Sim::BulletState> &bullets = m_Sim->Bullets();
    std::unordered_set<std::uint32_t> present;
    present.reserve(bullets.size());
    for (const Sim::BulletState &b : bullets) {
        present.insert(b.id);
    }
    // Release views whose sim bullet is gone.
    for (auto it = m_BulletViews.begin(); it != m_BulletViews.end();) {
        if (present.find(it->first) == present.end()) {
            m_Renderer.RemoveChild(it->second);
            it->second->Deactivate();
            m_BulletPool.Release(it->second);
            it = m_BulletViews.erase(it);
        } else {
            ++it;
        }
    }
    // Acquire new views; mirror every live bullet's position.
    for (const Sim::BulletState &b : bullets) {
        auto found = m_BulletViews.find(b.id);
        std::shared_ptr<Bullet> view;
        if (found == m_BulletViews.end()) {
            view = m_BulletPool.Acquire();
            view->Init(b.pos, b.vel, kBulletLifeMs, b.damage, b.camp); // arms the sprite; not Update()d.
            m_Renderer.AddChild(view);
            m_BulletViews.emplace(b.id, view);
        } else {
            view = found->second;
        }
        view->m_Transform.translation = b.pos;
    }
}

bool GameScene::RoomHasLiveHostile(int roomId) const {
    for (const Sim::Simulation::EntityView &ev : m_Sim->EnemyViews()) {
        if (ev.alive && ev.roomId == roomId) {
            return true;
        }
    }
    if (m_Sim->HasBoss()) {
        const Sim::Simulation::EntityView bv = m_Sim->BossView();
        if (bv.alive && bv.roomId == roomId) {
            return true;
        }
    }
    return false;
}

void GameScene::Update(float dtMs) {
    if (Util::Input::IsKeyUp(Util::Keycode::ESCAPE) || Util::Input::IfExit()) {
        Core::Context::GetInstance()->SetExit(true);
        return;
    }

    // --- Player movement with axis-separated wall sliding (stays scene-side) ---
    const glm::vec2 before = m_Player->Position();
    m_Player->Update(dtMs);
    const glm::vec2 after = m_Player->Position();
    glm::vec2 resolved = before;
    if (!BlocksAny(glm::vec2(after.x, before.y), kPlayerRadius)) {
        resolved.x = after.x;
    }
    if (!BlocksAny(glm::vec2(resolved.x, after.y), kPlayerRadius)) {
        resolved.y = after.y;
    }
    m_Player->m_Transform.translation = resolved;

    // --- Energy regen (scene-owned) ---
    m_EnergyRegenAccumMs += dtMs;
    while (m_EnergyRegenAccumMs >= kEnergyRegenMs) {
        m_EnergyRegenAccumMs -= kEnergyRegenMs;
        m_Player->Stats().AddEnergy(1);
    }

    // --- Which room is the player in (awake gating + clear-room) ---
    int playerRoomId = -1;
    for (std::size_t i = 0; i < m_Rooms.size(); ++i) {
        const glm::vec2 c = m_Rooms[i]->Center();
        const glm::vec2 hs = m_Rooms[i]->Size() * 0.5F;
        if (resolved.x >= c.x - hs.x && resolved.x <= c.x + hs.x &&
            resolved.y >= c.y - hs.y && resolved.y <= c.y + hs.y) {
            playerRoomId = static_cast<int>(i);
            break; // player is in exactly one room
        }
    }

    // --- Drive the deterministic sim ---
    Sim::WorldInputs in;
    in.playerPos = resolved;
    in.aimDir = AimDirection();
    in.firing = Util::Input::IsKeyPressed(Util::Keycode::MOUSE_LB) &&
                m_Player->Stats().energy >= m_WeaponEnergyCost;
    in.playerAlive = !m_Player->Stats().IsDead();
    in.playerRoomId = playerRoomId;

    m_Sim->SetPlayerStats(m_Player->Stats());      // push current vitals in
    m_Sim->Advance(dtMs, in);                       // sim damages its player-stats copy
    const CombatStats &simPlayer = m_Sim->PlayerStats();
    // MARKER (decision C): pull back ONLY hp + armor. Energy is scene-owned (regen + spend
    // below); the sim never modifies energy, so do NOT copy simPlayer.energy back -- doing so
    // would clobber this frame's regen/spend with the value we pushed in. Intentional asymmetry.
    m_Player->Stats().hp = simPlayer.hp;
    m_Player->Stats().armor = simPlayer.armor;
    for (int s = 0; s < m_Sim->PlayerShotsLastAdvance(); ++s) {
        m_Player->Stats().SpendEnergy(m_WeaponEnergyCost);
    }

    // --- Clear-room gating from sim liveness ---
    m_LockedRoom = (playerRoomId >= 0 && RoomHasLiveHostile(playerRoomId)) ? playerRoomId : -1;

    // --- Sync enemy/boss render views from the sim (entities are never erased: null on death) ---
    const std::vector<Sim::Simulation::EntityView> eviews = m_Sim->EnemyViews();
    for (const Sim::Simulation::EntityView &ev : eviews) {
        if (ev.id >= m_Enemies.size()) {
            continue;
        }
        std::shared_ptr<Enemy> &view = m_Enemies[ev.id];
        if (view == nullptr) {
            continue;
        }
        view->m_Transform.translation = ev.pos;
        if (!ev.alive) {
            m_Renderer.RemoveChild(view);
            view = nullptr;
        }
    }
    if (!m_Bosses.empty() && m_Bosses[0] != nullptr && m_Sim->HasBoss()) {
        const Sim::Simulation::EntityView bv = m_Sim->BossView();
        m_Bosses[0]->m_Transform.translation = bv.pos;
        if (!bv.alive) {
            m_Renderer.RemoveChild(m_Bosses[0]);
            m_Bosses[0] = nullptr;
            LOG_INFO("Boss defeated!");
        }
    }

    // --- Sync bullet views ---
    SyncBulletViews();

    // --- Player death ---
    if (m_Player->Stats().IsDead()) {
        LOG_INFO("Player defeated -- exiting");
        Core::Context::GetInstance()->SetExit(true);
        return;
    }

    // --- Chests: open on proximity, roll loot, drop a weapon pickup ---
    const glm::vec2 playerPos = resolved;
    for (auto &chest : m_Chests) {
        if (chest->Opened() ||
            glm::distance(playerPos, chest->Position()) > kChestOpenRange) {
            continue;
        }
        chest->Open();
        const std::string dropId = m_Loot.Roll(chest->Tier(), m_Rng);
        if (const WeaponDef *def = m_Data.ResolveDropWeapon(dropId)) {
            auto pickup = std::make_shared<WeaponPickup>(
                std::string(RESOURCE_DIR),
                chest->Position() + glm::vec2(0.0F, -kCellPx), def);
            m_Pickups.push_back(pickup);
            m_Renderer.AddChild(pickup);
        }
    }

    // --- Pickups: walk over one to equip it (rebuilds the sim WeaponController) ---
    for (auto it = m_Pickups.begin(); it != m_Pickups.end();) {
        if (glm::distance(playerPos, (*it)->Position()) <= kPickupRange) {
            const WeaponDef *def = (*it)->Def();
            ++m_WeaponSwaps;
            m_Sim->EquipWeapon(*def, def->id, m_RunSeed + 5 + m_WeaponSwaps);
            m_WeaponEnergyCost = def->consume > 0 ? def->consume : 1;
            m_Renderer.RemoveChild(*it);
            it = m_Pickups.erase(it);
        } else {
            ++it;
        }
    }

    // --- Camera follow ---
    m_Camera.Follow(m_Player->Position(), 0.1F);
    m_Camera.Update(dtMs);
}

void GameScene::Render() {
    Util::SetActiveViewMatrix(m_Camera.GetViewMatrix());
    m_Renderer.Update();
    Util::SetActiveViewMatrix(glm::mat4(1.0F)); // screen-space from here on
    m_Hud.Draw(m_Player->Stats());
}

} // namespace Game
